#!/usr/bin/env python2.7
"""Make some text python str.format friendly.

2012/09/28
Edward Liaw
"""
from __future__ import print_function
import sys
import argparse


def make_format_compatible(line):
    """Make the string compatible with the string format specifier."""
    return line.replace('\\', '\\\\').replace('{', '{{').replace('}', '}}').replace('"', '\\"').replace("'", "\\'")


def parse_arguments():
    """Handle command-line arguments.

    Returns:
        args: Arguments passed in from the command-line."""
    parser = argparse.ArgumentParser(description=__doc__,
                                     fromfile_prefix_chars='@')
    parser.add_argument('infile',
                        type=argparse.FileType('r'), nargs='?',
                        default=sys.stdin, help='input file')
    parser.add_argument('outfile',
                        type=argparse.FileType('w'), nargs='?',
                        default=sys.stdout, help='output file')
    return parser.parse_args()


def main():
    args = parse_arguments()

    # Handle I/O.
    with args.infile as infile, args.outfile as outfile:
        for line in infile:
            print(make_format_compatible(line), end='', file=outfile)


if __name__ == "__main__":
    main()
